# .gitpod.yml
image: mcr.microsoft.com/playwright:v1.46.1-jammy

tasks:
    - name: Setup, Install
      init: npm install
      command: npm run test

ports:
  - port: 9323
    onOpen: ignore

vscode:
  extensions:
    - ms-playwright.playwright
