# .gitpod.yml
image: gitpod/workspace-full

tasks:
    - name: Setup, Install
      init: npm install
      command: npm run test

ports:
  - port: 9323
    onOpen: ignore

vscode:
  extensions:
    - ms-playwright.playwright
