name: HyperExecute-Autosplit-2-Concurrency
on:
  workflow_dispatch
        
jobs:
  HyperExecute-Autosplit-2-Concurrency:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Download CLI and Setting Environment Variables
        shell: bash
        run: |
          curl https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute -o hyperexecute
          chmod +x hyperexecute
      
      - name: Executing the Job
        shell: bash
        run: |
          ./hyperexecute --user ${{ secrets.LT_USERNAME }} --key ${{ secrets.LT_ACCESS_KEY }} --download-artifacts --config cloud/win/execution.yaml
          ./hyperexecute --user ${{ secrets.LT_USERNAME }} --key ${{ secrets.LT_ACCESS_KEY }} --download-artifacts --config cloud/linux/execution.yaml
          echo "Test completion"